# docker run --name mssql -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD=Password123 -p 1433:1433 -u root -v mssql:/var/opt/mssql/data -d mcr.microsoft.com/mssql/server:2022-latest
# docker run --name postgres -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=password -p 5432:5432 -v postgres:/var/lib/postgresql/data -d postgres:latest
# docker run --name mongo -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password -p 27017:27017 -v mongo:/data/db -v mongoconf:/data/configdb -d mongo:latest
# docker run --name pgadmin4 -e PGADMIN_DEFAULT_EMAIL=admin@postgres.com -e PGADMIN_DEFAULT_PASSWORD=password -p 8080:80 -v pgadmin4:/var/lib/pgadmin -d dpage/pgadmin4:latest
version: '3.9'

name: database
services:
  mssql:
    container_name: mssql_container
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password
    volumes:
      - mssql_data:/var/opt/mssql/data
  postgres:
    container_name: postgres_container
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    container_name: mongodb_container
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.2
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  postgres_data:
  mssql_data:
  mongo_data:
  mongo_config:
